Traceback (most recent call last):
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
########################################################################################
# Direct matrix inversion will not work for overdetermined system                      #
########################################################################################

A = np.linalg.solve(Xa, Ya)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mLinAlgError[0m                               Traceback (most recent call last)
Cell [1;32mIn[22], line 5[0m
[0;32m      1[0m [38;5;66;03m########################################################################################[39;00m
[0;32m      2[0m [38;5;66;03m# Direct matrix inversion will not work for overdetermined system                      #[39;00m
[0;32m      3[0m [38;5;66;03m########################################################################################[39;00m
[1;32m----> 5[0m A [38;5;241m=[39m np[38;5;241m.[39mlinalg[38;5;241m.[39msolve(Xa, Ya)

File [1;32m~\anaconda3\Lib\site-packages\numpy\linalg\_linalg.py:399[0m, in [0;36msolve[1;34m(a, b)[0m
[0;32m    397[0m a, _ [38;5;241m=[39m _makearray(a)
[0;32m    398[0m _assert_stacked_2d(a)
[1;32m--> 399[0m _assert_stacked_square(a)
[0;32m    400[0m b, wrap [38;5;241m=[39m _makearray(b)
[0;32m    401[0m t, result_t [38;5;241m=[39m _commonType(a, b)

File [1;32m~\anaconda3\Lib\site-packages\numpy\linalg\_linalg.py:202[0m, in [0;36m_assert_stacked_square[1;34m(*arrays)[0m
[0;32m    200[0m m, n [38;5;241m=[39m a[38;5;241m.[39mshape[[38;5;241m-[39m[38;5;241m2[39m:]
[0;32m    201[0m [38;5;28;01mif[39;00m m [38;5;241m!=[39m n:
[1;32m--> 202[0m     [38;5;28;01mraise[39;00m LinAlgError([38;5;124m'[39m[38;5;124mLast 2 dimensions of the array must be square[39m[38;5;124m'[39m)

[1;31mLinAlgError[0m: Last 2 dimensions of the array must be square

