Traceback (most recent call last):
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jqbond\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Load Experimental Data; convert to numpy arrays

#Experiment 1 with Chromium ion concentration at 0.1M
file = open("EXP1.csv")
csvreader = csv.reader(file)
rows = []
for row in csvreader:
     rows.append(row)
file.close()
EXP1 = np.array(rows, dtype = 'float')
CS1  = EXP1[:,0]
CI1  = EXP1[:,1]
r1   = EXP1[:,2]

#Experiment 2 with Chromium ion concentration at 0.5M
file = open("EXP2.csv")
csvreader = csv.reader(file)
rows = []
for row in csvreader:
     rows.append(row)
file.close()
EXP2 = np.array(rows, dtype = 'float')
CS2  = EXP2[:,0]
CI2  = EXP2[:,1]
r2   = EXP2[:,2]

#Experiment 3 with Chromium ion concentration at 0.005M
file = open("EXP3.csv")
csvreader = csv.reader(file)
rows = []
for row in csvreader:
     rows.append(row)
file.close()
EXP3 = np.array(rows, dtype = 'float')
CS3  = EXP3[:,0]
CI3  = EXP3[:,1]
r3   = EXP3[:,2]

#Experiment 4 with Chromium ion concentration at 1.25M
file = open("EXP4.csv")
csvreader = csv.reader(file)
rows = []
for row in csvreader:
     rows.append(row)
file.close()
EXP4 = np.array(rows, dtype = 'float')
CS4  = EXP4[:,0]
CI4  = EXP4[:,1]
r4   = EXP4[:,2]
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_9020\993742937.py[0m in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [1;31m#Experiment 1 with Chromium ion concentration at 0.1M[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [0mfile[0m [1;33m=[0m [0mopen[0m[1;33m([0m[1;34m"EXP1.csv"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [0mcsvreader[0m [1;33m=[0m [0mcsv[0m[1;33m.[0m[0mreader[0m[1;33m([0m[0mfile[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mrows[0m [1;33m=[0m [1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'EXP1.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'EXP1.csv'

