Traceback (most recent call last):
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jqbond\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = np.linalg.solve(Xa, Ya)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mLinAlgError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_18560\2358220363.py[0m in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[1;33m [0mA[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinalg[0m[1;33m.[0m[0msolve[0m[1;33m([0m[0mXa[0m[1;33m,[0m [0mYa[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m<__array_function__ internals>[0m in [0;36msolve[1;34m(*args, **kwargs)[0m

[1;32m~\anaconda3\lib\site-packages\numpy\linalg\linalg.py[0m in [0;36msolve[1;34m(a, b)[0m
[0;32m    378[0m     [0ma[0m[1;33m,[0m [0m_[0m [1;33m=[0m [0m_makearray[0m[1;33m([0m[0ma[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    379[0m     [0m_assert_stacked_2d[0m[1;33m([0m[0ma[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 380[1;33m     [0m_assert_stacked_square[0m[1;33m([0m[0ma[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    381[0m     [0mb[0m[1;33m,[0m [0mwrap[0m [1;33m=[0m [0m_makearray[0m[1;33m([0m[0mb[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    382[0m     [0mt[0m[1;33m,[0m [0mresult_t[0m [1;33m=[0m [0m_commonType[0m[1;33m([0m[0ma[0m[1;33m,[0m [0mb[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numpy\linalg\linalg.py[0m in [0;36m_assert_stacked_square[1;34m(*arrays)[0m
[0;32m    201[0m         [0mm[0m[1;33m,[0m [0mn[0m [1;33m=[0m [0ma[0m[1;33m.[0m[0mshape[0m[1;33m[[0m[1;33m-[0m[1;36m2[0m[1;33m:[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    202[0m         [1;32mif[0m [0mm[0m [1;33m!=[0m [0mn[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 203[1;33m             [1;32mraise[0m [0mLinAlgError[0m[1;33m([0m[1;34m'Last 2 dimensions of the array must be square'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    204[0m [1;33m[0m[0m
[0;32m    205[0m [1;32mdef[0m [0m_assert_finite[0m[1;33m([0m[1;33m*[0m[0marrays[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mLinAlgError[0m: Last 2 dimensions of the array must be square
LinAlgError: Last 2 dimensions of the array must be square

