Traceback (most recent call last):
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jqbond\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbond\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def volcalc(N):
    FAf = 1 #mol/min
    CAf = 1 #mol/L
    k   = 1 #1/min
    XA  = 0.9
    DX  = XA/N
    
    reactorset = np.linspace(1, N, N)
    V   = np.zeros(N)
    
    for index, n in enumerate(reactorset):
         V[index] = FAf/CAf/k*DX/(1 - n*DX)
    Vtot = sum(V)
    return [Vtot, V]
volcalc(1.0)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_14724\1397176298.py[0m in [0;36m<cell line: 15>[1;34m()[0m
[0;32m     13[0m     [0mVtot[0m [1;33m=[0m [0msum[0m[1;33m([0m[0mV[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m     [1;32mreturn[0m [1;33m[[0m[0mVtot[0m[1;33m,[0m [0mV[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 15[1;33m [0mvolcalc[0m[1;33m([0m[1;36m1.0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Temp\ipykernel_14724\1397176298.py[0m in [0;36mvolcalc[1;34m(N)[0m
[0;32m      6[0m     [0mDX[0m  [1;33m=[0m [0mXA[0m[1;33m/[0m[0mN[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m [1;33m[0m[0m
[1;32m----> 8[1;33m     [0mreactorset[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;36m1[0m[1;33m,[0m [0mN[0m[1;33m,[0m [0mN[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      9[0m     [0mV[0m   [1;33m=[0m [0mnp[0m[1;33m.[0m[0mzeros[0m[1;33m([0m[0mN[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     10[0m [1;33m[0m[0m

[1;32m<__array_function__ internals>[0m in [0;36mlinspace[1;34m(*args, **kwargs)[0m

[1;32m~\anaconda3\lib\site-packages\numpy\core\function_base.py[0m in [0;36mlinspace[1;34m(start, stop, num, endpoint, retstep, dtype, axis)[0m
[0;32m    118[0m [1;33m[0m[0m
[0;32m    119[0m     """
[1;32m--> 120[1;33m     [0mnum[0m [1;33m=[0m [0moperator[0m[1;33m.[0m[0mindex[0m[1;33m([0m[0mnum[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    121[0m     [1;32mif[0m [0mnum[0m [1;33m<[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    122[0m         [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34m"Number of samples, %s, must be non-negative."[0m [1;33m%[0m [0mnum[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: 'float' object cannot be interpreted as an integer
TypeError: 'float' object cannot be interpreted as an integer

